### PR TITLE
Fixed button borders and margin and added installation example to README

### PR DESCRIPTION
**Pull request by damassi**
The current button borders appear choppy and not too smooth.  This PR fixes that as well as a few alignments between the margins and padding and updates the README with a possible installation.

### CODE REVIEW

**Comment by iktl** [comment]
Thanks @damassi, these changes look good!

**Comment by damassi** [comment]
Awesome!  Great work on this BTW.

**Comment by damassi** [comment]
(Could you bump the NPM version if you're not in the middle of something?  If so, please ignore : )

**Comment by iktl** [comment]
Just bumped it now.

**Comment by damassi** [comment]
Appreciated ++

**Pull request merged**
